--- @class Groups
local M = {}

local colors = require("maggot.palette")

M.setup = function()
    return {
        Normal = { fg = colors.fg, bg = colors.bg },
        NormalFloat = { fg = colors.fg, bg = colors.bg },
        Comment = { fg = colors.comment, italic = false },
        Constant = { fg = colors.number },
        String = { fg = colors.number },
        Character = { fg = colors.number },
        Number = { fg = colors.number },
        Boolean = { fg = colors.cyan },
        Float = { fg = colors.number },
        FloatBorder = { fg = colors.white },
        Operator = { fg = colors.operator },
        Keyword = { fg = colors.green },
        Keywords = { fg = colors.green },
        Identifier = { fg = colors.bright_green },
        Function = { fg = colors.yellow },
        Statement = { fg = colors.keyword },
        Conditional = { fg = colors.green },
        Repeat = { fg = colors.green },
        Label = { fg = colors.cyan },
        Exception = { fg = colors.subtle_green },
        PreProc = { fg = colors.yellow },
        Include = { fg = colors.subtle_green },
        Define = { fg = colors.subtle_green },
        Title = { fg = colors.cyan },
        Macro = { fg = colors.constant },
        PreCondit = { fg = colors.cyan },
        Type = { fg = colors.fg },
        StorageClass = { fg = colors.subtle_green },
        Structure = { fg = colors.yellow },
        TypeDef = { fg = colors.yellow },
        Special = { fg = colors.number, italic = false },
        SpecialComment = { fg = colors.comment, italic = false },
        Error = { fg = colors.bright_red },
        Todo = { fg = colors.subtle_green, bold = true, italic = false },
        Underlined = { fg = colors.cyan, underline = true },

        Cursor = { fg = colors.cursor },
        CursorLineNr = { fg = colors.fg, bold = true },

        SignColumn = { bg = colors.bg },

        Conceal = { fg = colors.comment },
        CursorColumn = { bg = colors.black },
        CursorLine = { bg = colors.selection },
        ColorColumn = { bg = colors.selection },

        StatusLine = { fg = colors.statusline, bg = colors.black },
        StatusLineNC = { fg = colors.comment },
        StatusLineTerm = { fg = colors.white, bg = colors.black },
        StatusLineTermNC = { fg = colors.comment },

        Directory = { fg = colors.cyan },
        DiffAdd = { fg = colors.bg, bg = colors.number },
        DiffChange = { fg = colors.orange },
        DiffDelete = { fg = colors.red },
        DiffText = { fg = colors.comment },

        ErrorMsg = { fg = colors.bright_red },
        VertSplit = { fg = colors.black },
        WinSeparator = { fg = colors.black },
        Folded = { fg = colors.comment },
        FoldColumn = {},
        Search = { fg = colors.black, bg = colors.number },
        IncSearch = { fg = colors.number, bg = colors.comment },
        LineNr = { fg = colors.comment },
        MatchParen = { fg = colors.fg, underline = true },
        NonText = { fg = colors.nontext },
        Pmenu = { fg = colors.white, bg = colors.menubg },
        PmenuSel = { fg = colors.white, bg = colors.selection },
        PmenuSbar = { bg = colors.bg },
        PmenuThumb = { bg = colors.selection },

        Question = { fg = colors.subtle_green },
        QuickFixLine = { fg = colors.black, bg = colors.yellow },
        SpecialKey = { fg = colors.nontext },

        SpellBad = { fg = colors.bright_red, underline = true },
        SpellCap = { fg = colors.yellow },
        SpellLocal = { fg = colors.yellow },
        SpellRare = { fg = colors.yellow },

        TabLine = { fg = colors.comment },
        TabLineSel = { fg = colors.white },
        TabLineFill = { bg = colors.bg },
        Terminal = { fg = colors.white, bg = colors.black },
        Visual = { bg = colors.visual },
        VisualNOS = { fg = colors.visual },
        WarningMsg = { fg = colors.yellow },
        WildMenu = { fg = colors.black, bg = colors.white },

        -- TreeSitter
        ["@error"] = { fg = colors.diag_error },
        ["@punctuation.delimiter"] = { fg = colors.fg },
        ["@punctuation.bracket"] = { fg = colors.fg },
        ["@punctuation.special"] = { fg = colors.fg },

        ["@constant"] = { fg = colors.constant },
        ["@constant.builtin"] = { fg = colors.constant },
        ["@symbol"] = { fg = colors.constant },

        ["@constant.macro"] = { fg = colors.constant },
        ["@string.regex"] = { fg = colors.red },
        ["@string"] = { fg = colors.string },
        ["@string.escape"] = { fg = colors.cyan },
        ["@character"] = { fg = colors.number },
        ["@number"] = { fg = colors.number },
        ["@boolean"] = { fg = colors.yellow },
        ["@float"] = { fg = colors.number },
        ["@annotation"] = { fg = colors.yellow },
        ["@attribute"] = { fg = colors.cyan },
        ["@namespace"] = { fg = colors.number },

        ["@function.builtin"] = { fg = colors.Function, bold = true },
        ["@function"] = { fg = colors.Function, bold = true },
        ["@function.macro"] = { fg = colors.Function },
        ["@parameter"] = { fg = colors.yellow },
        ["@parameter.reference"] = { fg = colors.yellow },
        ["@method"] = { fg = colors.number },
        ["@field"] = { fg = colors.number },
        ["@property"] = { fg = colors.type },
        ["@constructor"] = { fg = colors.cyan },

        ["@conditional"] = { fg = colors.bright_subtle_green },
        ["@repeat"] = { fg = colors.bright_subtle_green },
        ["@label"] = { fg = colors.cyan },

        ["@keyword"] = { fg = colors.keyword, bold = true },
        ["@keyword.function"] = { fg = colors.Function },
        ["@keyword.function.ruby"] = { fg = colors.Function },
        ["@keyword.operator"] = { fg = colors.bright_green },
        ["@operator"] = { fg = colors.bright_green },
        ["@exception"] = { fg = colors.bright_red },
        ["@type"] = { fg = colors.bright_cyan },
        ["@type.builtin"] = { fg = colors.cyan, italic = true },
        ["@type.qualifier"] = { fg = colors.bright_subtle_green },
        ["@structure"] = { fg = colors.constant },
        ["@include"] = { fg = colors.subtle_green },

        ["@variable"] = { fg = colors.variable },
        ["@variable.builtin"] = { fg = colors.variable },

        ["@text"] = { fg = colors.number },
        ["@text.strong"] = { fg = colors.number, bold = true }, -- bold
        ["@text.emphasis"] = { fg = colors.yellow, italic = true }, -- italic
        ["@text.underline"] = { fg = colors.number },
        ["@text.title"] = { fg = colors.subtle_green, bold = true }, -- title
        ["@text.literal"] = { fg = colors.number }, -- inline code
        ["@text.uri"] = { fg = colors.yellow, italic = true }, -- urls
        ["@text.reference"] = { fg = colors.number, bold = true },

        ["@tag"] = { fg = colors.cyan },
        ["@tag.attribute"] = { fg = colors.number },
        ["@tag.delimiter"] = { fg = colors.subtle_green },

        -- Semantic
        ["@class"] = { fg = colors.cyan },
        ["@struct"] = { fg = colors.cyan },
        ["@enum"] = { fg = colors.cyan },
        ["@enumMember"] = { fg = colors.constant },
        ["@event"] = { fg = colors.cyan },
        ["@interface"] = { fg = colors.cyan },
        ["@modifier"] = { fg = colors.cyan },
        ["@regexp"] = { fg = colors.yellow },
        ["@typeParameter"] = { fg = colors.cyan },
        ["@decorator"] = { fg = colors.cyan },

        -- LSP Semantic (0.9+)
        ["@lsp.type.class"] = { fg = colors.cyan },
        ["@lsp.type.enum"] = { fg = colors.cyan },
        ["@lsp.type.decorator"] = { fg = colors.number },
        ["@lsp.type.enumMember"] = { fg = colors.constant },
        ["@lsp.type.function"] = { fg = colors.number },
        ["@lsp.type.interface"] = { fg = colors.bright_yellow },
        ["@lsp.type.macro"] = { fg = colors.cyan },
        ["@lsp.type.method"] = { fg = colors.number },
        ["@lsp.type.namespace"] = { fg = colors.number },
        ["@lsp.type.parameter"] = { fg = colors.yellow },
        ["@lsp.type.property"] = { fg = colors.bright_subtle_green },
        ["@lsp.type.struct"] = { fg = colors.cyan },
        ["@lsp.type.type"] = { fg = colors.yellow },
        ["@lsp.type.variable"] = { fg = colors.fg },

        -- HTML
        htmlArg = { fg = colors.orange },
        htmlBold = { fg = colors.yellow, bold = true },
        htmlEndTag = { fg = colors.cyan },
        htmlH1 = { fg = colors.subtle_green },
        htmlH2 = { fg = colors.subtle_green },
        htmlH3 = { fg = colors.subtle_green },
        htmlH4 = { fg = colors.subtle_green },
        htmlH5 = { fg = colors.subtle_green },
        htmlH6 = { fg = colors.subtle_green },
        htmlItalic = { fg = colors.constant, italic = true },
        htmlLink = { fg = colors.subtle_green, underline = true },
        htmlSpecialChar = { fg = colors.yellow },
        htmlSpecialTagName = { fg = colors.cyan },
        htmlTag = { fg = colors.cyan },
        htmlTagN = { fg = colors.cyan },
        htmlTagName = { fg = colors.cyan },
        htmlTitle = { fg = colors.white },

        -- Markdown
        markdownBlockquote = { fg = colors.yellow, italic = true },
        markdownBold = { fg = colors.orange, bold = true },
        markdownCode = { fg = colors.orange },
        markdownCodeBlock = { fg = colors.orange },
        markdownCodeDelimiter = { fg = colors.red },
        markdownH1 = { fg = colors.subtle_green, bold = true },
        markdownH2 = { fg = colors.orange, bold = true },
        markdownH3 = { fg = colors.bright_red, bold = true },
        markdownH4 = { fg = colors.yellow, bold = true },
        markdownH5 = { fg = colors.bright_cyan, bold = true },
        markdownH6 = { fg = colors.yellow, bold = true },
        markdownHeadingDelimiter = { fg = colors.red },
        markdownHeadingRule = { fg = colors.comment },
        markdownId = { fg = colors.subtle_green },
        markdownIdDeclaration = { fg = colors.cyan },
        markdownIdDelimiter = { fg = colors.subtle_green },
        markdownItalic = { fg = colors.yellow, italic = true },
        markdownLinkDelimiter = { fg = colors.subtle_green },
        markdownLinkText = { fg = colors.blue },
        markdownListMarker = { fg = colors.cyan },
        markdownOrderedListMarker = { fg = colors.red },
        markdownRule = { fg = colors.comment },

        --  Diff
        diffAdded = { fg = colors.orange },
        diffRemoved = { fg = colors.red },
        diffFileId = { fg = colors.yellow, bold = true, reverse = true },
        diffFile = { fg = colors.nontext },
        diffNewFile = { fg = colors.orange },
        diffOldFile = { fg = colors.red },

        debugPc = { bg = colors.menu },
        debugBreakpoint = { fg = colors.red, reverse = true },

        -- Git Signs
        GitSignsAdd = { fg = colors.number },
        GitSignsChange = { fg = colors.orange },
        GitSignsDelete = { fg = colors.bright_red },
        GitSignsAddLn = { fg = colors.black, bg = colors.number },
        GitSignsChangeLn = { fg = colors.black, bg = colors.orange },
        GitSignsDeleteLn = { fg = colors.black, bg = colors.bright_red },
        GitSignsCurrentLineBlame = { fg = colors.white },

        -- NvimTree
        NvimTreeNormal = { fg = colors.fg, bg = colors.menu },
        NvimTreeVertSplit = { fg = colors.bg, bg = colors.bg },
        NvimTreeRootFolder = { fg = colors.fg, bold = true },
        NvimTreeGitDirty = { fg = colors.yellow },
        NvimTreeGitNew = { fg = colors.number },
        NvimTreeImageFile = { fg = colors.blue },
        NvimTreeFolderIcon = { fg = colors.subtle_green },
        NvimTreeIndentMarker = { fg = colors.nontext },
        NvimTreeEmptyFolderName = { fg = colors.comment },
        NvimTreeFolderName = { fg = colors.fg },
        NvimTreeSpecialFile = { fg = colors.blue, underline = true },
        NvimTreeOpenedFolderName = { fg = colors.fg },
        NvimTreeCursorLine = { bg = colors.selection },
        NvimTreeIn = { bg = colors.selection },

        -- LSP
        DiagnosticError = { fg = colors.red },
        DiagnosticWarn = { fg = colors.yellow },
        DiagnosticInfo = { fg = colors.cyan },
        DiagnosticHint = { fg = colors.cyan },
        DiagnosticUnderlineError = { undercurl = true, sp = colors.red },
        DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
        DiagnosticUnderlineInfo = { undercurl = true, sp = colors.cyan },
        DiagnosticUnderlineHint = { undercurl = true, sp = colors.cyan },
        DiagnosticSignError = { fg = colors.red },
        DiagnosticSignWarn = { fg = colors.yellow },
        DiagnosticSignInfo = { fg = colors.cyan },
        DiagnosticSignHint = { fg = colors.cyan },
        DiagnosticFloatingError = { fg = colors.red },
        DiagnosticFloatingWarn = { fg = colors.yellow },
        DiagnosticFloatingInfo = { fg = colors.cyan },
        DiagnosticFloatingHint = { fg = colors.cyan },
        DiagnosticVirtualTextError = { fg = colors.red },
        DiagnosticVirtualTextWarn = { fg = colors.yellow },
        DiagnosticVirtualTextInfo = { fg = colors.cyan },
        DiagnosticVirtualTextHint = { fg = colors.cyan },

        LspDiagnosticsDefaultError = { fg = colors.red },
        LspDiagnosticsDefaultWarning = { fg = colors.yellow },
        LspDiagnosticsDefaultInformation = { fg = colors.cyan },
        LspDiagnosticsDefaultHint = { fg = colors.cyan },
        LspDiagnosticsUnderlineError = { fg = colors.red, undercurl = true },
        LspDiagnosticsUnderlineWarning = {
            fg = colors.yellow,
            undercurl = true,
        },
        LspDiagnosticsUnderlineInformation = {
            fg = colors.cyan,
            undercurl = true,
        },
        LspDiagnosticsUnderlineHint = { fg = colors.cyan, undercurl = true },
        LspReferenceText = { fg = colors.yellow, bg = colors.selection },
        LspReferenceRead = { fg = colors.yellow, bg = colors.selection },
        LspReferenceWrite = { fg = colors.yellow, bg = colors.selection },
        LspCodeLens = { fg = colors.cyan },
        LspInlayHint = { fg = colors.comment },

        -- Cmp
        CmpItemAbbr = { fg = colors.white, bg = colors.bg },
        CmpItemKind = { fg = colors.white, bg = colors.bg },
        CmpItemKindMethod = { link = "@method" },
        CmpItemKindText = { link = "@text" },
        CmpItemKindFunction = { link = "@function" },
        CmpItemKindConstructor = { link = "@type" },
        CmpItemKindVariable = { link = "@variable" },
        CmpItemKindClass = { link = "@type" },
        CmpItemKindInterface = { link = "@type" },
        CmpItemKindModule = { link = "@namespace" },
        CmpItemKindProperty = { link = "@property" },
        CmpItemKindOperator = { link = "@operator" },
        CmpItemKindReference = { link = "@parameter.reference" },
        CmpItemKindUnit = { link = "@field" },
        CmpItemKindValue = { link = "@field" },
        CmpItemKindField = { link = "@field" },
        CmpItemKindEnum = { link = "@field" },
        CmpItemKindKeyword = { link = "@keyword" },
        CmpItemKindSnippet = { link = "@text" },
        CmpItemKindEvent = { link = "@constant" },
        CmpItemKindEnumMember = { link = "@field" },
        CmpItemKindConstant = { link = "@constant" },
        CmpItemKindStruct = { link = "@structure" },
        CmpItemKindTypeParameter = { link = "@parameter" },
        BufferLineFill = { bg = colors.bg },
        BufferLineBackground = { bg = nil },
        BufferLineBufferSelected = { bg = nil },
        BufferLineBufferVisible = { bg = nil },
        BufferLineSeparator = { bg = nil },
        BufferLineSeparatorSelected = { bg = nil },
        BufferLineSeparatorVisible = { bg = nil },

        -- WinPicker
        WinPicker = { fg = colors.bg, bg = colors.number },
    }
end

return M
